project_id = "qbdgmouvkzrrlxrtnieo"

[functions.process-document]
verify_jwt = false

[functions.semantic-search]
verify_jwt = true

[functions.generate-answer]
verify_jwt = true

[functions.notion-auth]
verify_jwt = false

[functions.notion-import]
verify_jwt = true

[functions.google-drive-auth]
verify_jwt = false

[functions.google-drive-import]
verify_jwt = true

[functions.google-drive-sync]
verify_jwt = false
